#!/bin/sh

case "$1" in
    start)
        start-stop-daemon -S -a /usr/bin/aesdsocket -n aesdsocket -- -d
        ;;
    stop)
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage $0 {start|stop}"
    exit 1
esac
exit 0    
